name: lint_staged
description:
  Run linters on git staged files for your Flutter and Dart projects.
version: 0.2.0-dev.0
homepage: https://github.com/hyiso/lint_staged
repository: https://github.com/hyiso/lint_staged

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  chalk: ^1.2.1
  glob: ^2.0.1
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  commitlint_cli: ^0.2.1+1
  commitlint_config: ^0.1.1
  husky: ^0.1.4
  lints: ^2.0.0
  test: ^1.16.0

lint_staged:
  'lib/**.dart': dart fix --apply && dart format --fix